services:
  ts-proxy:
    image: tailscale/tailscale:latest
    container_name: ts-proxy
    hostname: ${TS_HOSTNAME_PROXY}
    env_file:
      - ../../shared/.env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./ts-proxy-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm-internal
    restart: unless-stopped
    network_mode: "service:ts-proxy"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    depends_on:
      - ts-proxy
