services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    command: /data/*.zim
    volumes:
      - ./data:/data
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwix.rule=Host(`kiwix.home.meshwa.space`)"
      - "traefik.http.routers.kiwix.entrypoints=websecure"
      - "traefik.http.routers.kiwix.tls=true"
      - "traefik.http.routers.kiwix.tls.certresolver=letsencrypt"
      - "traefik.http.services.kiwix.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kiwix-local.rule=Host(`kiwix.homeserver.com`)"
      - "traefik.http.routers.kiwix-local.entrypoints=websecure"
      - "traefik.http.routers.kiwix-local.tls=true"
      - "traefik.http.routers.kiwix-local.service=kiwix"

networks:
  proxy:
    external: true
    name: proxy
