services:
  honeygain:
    container_name: honeygain
    image: honeygain/honeygain:latest
    restart: always
    command: >
      -tou-accept
      -email ${HONEYGAIN_EMAIL}
      -pass ${HONEYGAIN_PASS}
      -device ${HONEYGAIN_DEVICE}
