services:
  code-server-init:
    image: alpine
    user: root
    volumes:
      - ./data:/home/coder/.local/share/code-server
    command: chown -R 1000:1000 /home/coder/.local/share/code-server

  code-server:
    depends_on:
      code-server-init:
        condition: service_completed_successfully
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_USER=meshwa
    user: "1000:1000"
    volumes:
      - /home/meshwa:/home/coder/projects
      - ./config:/home/coder/.config
      - ./data:/home/coder/.local/share/code-server
    networks:
      - proxy
    tty: true
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.rule=Host(`vscode.home.meshwa.space`)"
      - "traefik.http.routers.vscode.entrypoints=websecure"
      - "traefik.http.routers.vscode.tls=true"
      - "traefik.http.services.vscode.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
    name: proxy
