services:
  omnisearch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - ./locales:/app/locales
      - ./example-config.ini:/etc/omnisearch/config.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.rule=Host(`omnisearch.home.meshwa.space`)"
      - "traefik.http.routers.copyparty.entrypoints=websecure"
      - "traefik.http.routers.copyparty.tls=true"
      - "traefik.http.services.omnisearch.loadbalancer.server.port=8087"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
    name: proxy
